### ISSUE TITLE
PubSub messages aren't delivered

### ISSUE THREAD

**Issue by JonCanning** [rebus-org/Rebus.PostgreSql#21]
I've been playing around with Rebus, trying to set up pub sub with dead lettering and a SQL back end. It's written in F# but it's a simple example:

https://github.com/JonCanning/rebuspostgrespubsub

The same code works for MySql and SqlServer, but for Postgres the message stays in the `publisher` table and is never delivered to the subscriber.

I'm using a docker instance of postgres:

`docker run --name postgres -e POSTGRES_PASSWORD=password -p 5432:5432 -d postgres`

Can you help?

**Comment by mookid8000** [comment]
The Postgres transport is different from the other transports, because it uses a single table for all messages and not the table-per-queue model used by the MSSQL and MySQL transports.

If you pass something like `"Messages"` as the table name argument in the `UsePostgreSql(...)` lines, I bet it will make a difference 🙂

**Comment by JonCanning** [comment]
Perfect, thankyou
