### ISSUE TITLE
Some cleanup activity is infinitely failing within a transaction and being retried

### ISSUE THREAD

**Issue by sjd2021** [rebus-org/Rebus.PostgreSql#43]
I've added a [repro here](https://github.com/sjd2021/rebus.postgres-delete-issue-repro) using the elsa workflow project. They did not seem to have this issue with other flavors of rebus, so I'm hoping the issue can be resolved within this project.

Steps:

1. Create a database and enable pg_stat_statements
2. Run the repro program after pointing the connection string at your database (I am using docker, 14.3 alpine for my postgres instance)
3. Run the following query every few seconds and watch as it is run tens of thousands of times in a very short period of time (a minute?)

```
select query, calls, (total_exec_time/calls)::integer as avg_time_ms
from pg_stat_statements
where query ilike 'DELETE from %recipient%'
order by calls desc
limit 10;
```

example:
![image](https://github.com/rebus-org/Rebus.PostgreSql/assets/84007094/4eec8f43-766b-4559-9815-822b562882c8)

This is hammering our databases for some reason and making it difficult to use the postgres implementation of rebus in a production environment. 

Functionally, everything seems to work well outside of this cleanup job. I believe that something else in the transaction is failing *after* this delete is successfully executed, and whatever that is causes the whole transaction to be rolled back and retried.

**Comment by jmkelly** [comment]
That is that sql that selects the top message from the queue, locks it, and then deletes after processing.  Given that Rebus polls the database for messages, its expected you would get a lot of these calls because for every worker, it polls regularly.  This polling behavior can be modified though, at the expense of latency of picking up messages off the queue.

See https://github.com/jmkelly/rebus.postgres-delete-issue-repro/blob/62c372a7a936b5dc19af4a15de32fe15fcd1ffd6/PostgresRebusRepro/Repro/Program.cs#L61 for how to reduce polling to a single worker every second, it maybe worth playing with these two options to try to find the best compromise for your workloads.  

There's also more explanation of the backoff strategies at https://github.com/rebus-org/Rebus/wiki/Back-off-strategy, you may be able to implement something that better suits through that too.

**Comment by jmkelly** [comment]
> For my own understanding about default behavior/performance:
> 
>     1. To confirm, 50-100x executions of this query in a single second is actually _expected_ with the default settings?

I checked the default backoff, and its a request every 100ms for 1s, then every 250ms.  Given what we've seen, I'm assuming this is then multiplied by the MaxParallelism value.  Given the default MaxParallelism is 5, if my rough maths is correct, we would expect 50 requests in first second, then 20 request / s afterwards.  I'm not sure if its related though, but there is an async bottleneck in the transport that is fixed at 20, I'm wondering if this should be set to the MaxParallelism value?  I don't fully understand the relationship between these as I just copied from the MsSql transport at the time.

> 
>     2. I can see one rollback for every time the delete is called when I monitor the executions live via docker. I originally thought this was happening due to an exception, but  maybe it just doesn't have a reason to commit anything if it's empty.
> 
> 
I do see when consuming messages at full rate, the commits match up with the messages sent so I can only assume that when the queue is empty, the delete skip locked query takes a transaction, but then rolls back because there is nothing to commit.
![image](https://github.com/rebus-org/Rebus.PostgreSql/assets/124026/c2210423-5b0d-432c-97a0-833d1719918d)


I guess there could be an exception when the queue table is empty and that is forcing the rollback but I would have thought that would bubble up.  See how I go for time, but I may look into this further.
